#+TITLE: p2peace
#+DATE: <2015-09-28 月>
#+AUTHOR: p2peace
#+EMAIL: 
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:comment d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil stat:t tags:t tasks:t tex:t timestamp:t toc:t
#+OPTIONS: todo:t |:t
#+CREATOR: Emacs 24.4.2 (Org mode 8.2.9)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
# SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
# REVEAL_THEME: 
#+REVEAL_TRANS: fade
#+REVEAL_MATHJAX: false
# OPTIONS: org-reveal-mathjax:t
#+OPTIONS: reveal_controls:nil
#+REVEAL_ROOT: /

* p2peace

** summary
- Divided we fall, united we're fascists: Can we be protected in an
  innocence-preserving manner?

* the problem
** physical security
- Physical security sucks whether you're rich or poor

- The rich live in a condo [or a similar allegedely-protected space]. A
  "security" company installs cameras and alarm systems all over the place (a
  huge intel/paedo source, mind you) and are physically protected by an armed
  guard at thr lobby, This can deter common criminal (heads up: "uncommon" ones
  are not affected: https://archive.is/i6HcP#selection-357.0-365.44 ], but fails
  miserably once so-called social order collapses [e.g. a civil war]: the guard
  at the gate is either from the losing side (i.e. dead, or hiding in the
  mountains) or worse [i.e. looting the premises].

- The poor get the short end of the stick (unless they win a civil
  war :p). They're either "protected" by the police (serving the rich) or [if
  social order allows it] a gang [at least they're also protected from tax
  collectors]. If they try to organize in order to defend themselves, they're
  either a gang (threatened by both the state and rivaling gangs) or worse:
  someone declares them a "terrorist group" and then even the Magna Carta stops
  protecting them.

TL;DR - in order to be safe, you should be violent motherfokker (which is
dangerous to your mental health).

* the solution

Everyone well-versed in 70s Kung Fu movies knows that when a village is being
harassed by bandits. the last thing you want to do is appeal to the
emperor. What you get is soldiers looting and raping you instead of bandits (who
are at least a bit afraid of the law.

The proper solution according to that narrative is for the peasants to practice
Kung Fu. Since people are lazy, bandits should cause a "critical mass" of
discomfort in order to be arsed to train.

Despite the shortcomings of this method, it is more profound (as long as we're
talking about proper Kung Fu training (and not arm-the-poor schemes like the
"Free" Syrian Army or even sicker experiments like Somalia). If you "learn to
figh like any good boy should" [
https://www.youtube.com/watch?v=7xvRdcwyvH0&t=46 (fuck German copyright
mafia. Listen to the original if you live in the free world)], your goal is to
avoid conflict. No "smart weapon" can teach you that (lazy peasants).

** components

- cultural:
- technical:

* culture

* technical
